
-- creates master table wf mam, this table contains data of records 
-- created in cycle number and error messages during the processing of data generated.

CREATE TABLE WF_MAM_OP_HDR_TRLR(
    CYCLE_NUMBER DECIMAL(10, 0) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    TOTAL_RECORD_COUNT DECIMAL(10, 0),
    FILENAME VARCHAR(250),
    ERROR_MSG VARCHAR(100),
    STATUS VARCHAR(20)
);
	
--creates detail table for wf mam, this table contains all the records that are written to csv.	
CREATE TABLE WF_MAM_SRC_FILE(
	CYCLE_NUMBER decimal(10, 0) NOT NULL,
	SEQUENCE_NUMBER decimal(10, 0) NOT NULL,
	REFERENCE_NUMBER varchar(255) NOT NULL,
	SECONDARY_AUTH varchar(255) NOT NULL,
	CONSOLIDATED_NAME varchar(128) NOT NULL,
	DUE_DATE date NULL,
	AMOUNT_DUE decimal(20, 2) NOT NULL,
	INVOICE_NUMBER varchar(20) NOT NULL,
	INVOICE_DATE date NOT NULL,
	EMAIL varchar(128) NULL,
	ADDRESS varchar(100) NULL,
	ADDRESS_2 varchar(100) NULL,
	CITY varchar(50) NULL,
	STATE char(2) NULL,
	ZIP char(10) NULL,
	PHONE varchar(20) NULL,
	STATUS varchar(20) NULL,
	STATUS_INVOICE varchar(50) NULL,
	SUBMISSION_NUMBER int NULL,
	primary key(CYCLE_NUMBER, SEQUENCE_NUMBER )
	);
	
CREATE TABLE SPR_LOCATION(
	SUBMISSION_NUMBER int NOT NULL,
	ENTITY_NUMBER int NOT NULL,
	LOCATION char(4) NOT NULL,
	ADDR_1 char(40) NOT NULL,
	ADDR_2 char(40) NOT NULL,
	CITY char(40) NOT NULL,
	STATE char(2) NOT NULL,
	ZIP1 char(5) NOT NULL
	);
	
CREATE TABLE SPR_INSURED_CONTACT_(
	CONTACT_CODE_ID int NOT NULL,
	SUBMISSION_NUMBER int NOT NULL,
	FIRST_NAME char(20) NOT NULL,
	LAST_NAME char(35) NOT NULL,
	EMAIL_ADDRESS char(80) NOT NULL,
	PHONE_AREA_CODE int NOT NULL,
	PHONE_PREFIX int NOT NULL,
	PHONE_SUFFIX int NOT NULL	
	);
	
CREATE TABLE SPR_DBA(
	SUBMISSION_NUMBER int NOT NULL,
	ENTITY_NUMBER int NOT NULL,
	DBA_NUMBER int NOT NULL,
	DBA_NAME char(80)
	);

CREATE TABLE SPR_ENTITY_FILE(
	SUBMISSION_NUMBER int,
	NEXT_DBA_NUMBER int,
	ENTITY_NUMBER int,
	ENTITY_NAME char(80)
	);

	--create COLLECTION_MASTER table
     CREATE TABLE COLLECTION_MASTER(
             COLLECTION_REC_ID   int  NOT NULL,
             POLICY_PREFIX_1   char(2) NOT NULL,
             POLICY_PREFIX_2   char(1) NOT NULL,
             POLICY_NUMBER   decimal(11, 0) NOT NULL,
             POLICY_SUFFIX   char(2) NOT NULL,
             SUBMISSION_NUMBER   int  NOT NULL,
             AGENCYDIR_COLLECTOR   char(8) NOT NULL,
             AGENCYDIR_INDICATOR   char(1) NOT NULL,
             ORIG_AGENCY_CODE   char(8) NOT NULL,
             DIRECT_COLLECTOR   char(8) NOT NULL,
             BILLING_PD_FROM   datetime  NULL,
             BILLING_PD_TO   datetime  NULL,
             DATE_CLEARED   datetime  NULL,
             DATE_PRINTED   datetime  NULL,
             AUDIT_INVOICE_NUMBER   int  NOT NULL,
             TRANSACTION_CODE   int  NOT NULL,
             GROSS_PREMIUM_AMOUNT   decimal(10, 2) NOT NULL,
             COMMISSION_AMOUNT   decimal(10, 2) NOT NULL,
             NET_PREMIUM_AMOUNT   decimal(10, 2) NOT NULL,
             GROSS_PAYMENT_APPLIE   decimal(10, 2) NOT NULL,
             ENTRY_DATE   datetime  NULL,
             CASH_APPL_TYPE   char(2) NOT NULL,
             NET_PAYMENT_APPLIED   decimal(10, 2) NOT NULL,
             RECORD_TYPE   int  NOT NULL,
             CLEARED_RECEIVABLE   char(1) NOT NULL,
             CASH_RECORD_ID   int  NOT NULL,
             COLLECT_REASON_CODE   int  NOT NULL,
             TRANSFER_FLAG   char(1) NOT NULL,
             AGENCYDIRECT_BILL   char(1) NOT NULL,
             ORIGINAL_ENTRY_DATE   datetime  NULL,
             O_COMMENT   char(60) NOT NULL,
             DATE_OF_COMMENT   datetime  NULL,
             ORIGINAL_TRANS_CODE   int  NOT NULL,
             COMMISSION_PAID_DATE   datetime  NULL,
             TIME_CREATED   char(8) NOT NULL,
             DIRECT_BILL_INVOICE   int  NOT NULL,
             COMMISSION   decimal(10, 9) NOT NULL,
             USERID   char(10) NOT NULL,
             COMMISSION_CLEARED   char(1) NOT NULL,
             COMMISSION_BASE_AMT   decimal(8, 0) NOT NULL,
             GL_COMPANY_CODE   int  NOT NULL,
             RECORD_CLEARED_ID   int  NOT NULL,
             ACCOUNT_CURRENT   char(1) NOT NULL,
             ACCOUNT_CURRENT_DATE   datetime  NULL,
             AMOUNT_XFERRED   decimal(10, 2) NOT NULL,
             XFER_POLICY_PREFIX_1   char(2) NOT NULL,
             XFER_POLICY_PREFIX_2   char(1) NOT NULL,
             XFER_POLICY_NUMBER   decimal(11, 0) NOT NULL,
             XFER_POLICY_SUFFIX   char(2) NOT NULL,
             XFER_ID   int  NOT NULL,
             POLICY_STATE_IDC   int  NOT NULL,
             DEFERRAL_PERCENT   decimal(9,8) NOT NULL,
             DEFERRAL_GROSS_AMOUN   decimal(10, 2) NOT NULL,
             DEFERRAL_COMM_AMOUNT   decimal(10, 2) NOT NULL,
             DEFERRAL_NET_AMOUNT   decimal(10, 2) NOT NULL,
             SEQUENCENUMBER  decimal(12, 0) NOT NULL
             );

    --create SP_BILL_STMT_CTRL table
    CREATE TABLE SP_BILL_STMT_CTRL(
        POLICY_PREFIX_1 char(2) NOT NULL,
        POLICY_PREFIX_2 char(1) NOT NULL,
        POLICY_NUMBER decimal(11, 0) NOT NULL,
        POLICY_SUFFIX char(2) NOT NULL,
        STMT_DATE datetime NULL,
        DUE_DATE datetime NULL,
        ENTRY_DATE datetime NULL,
        DATE_PRINTED datetime NULL,
        INVOICE_NUMBER int NOT NULL,
        AMOUNT_DUE decimal(10, 2) NOT NULL,
        PENDING_CANCEL_DATE datetime NULL,
        REVIEWED_FOR_CANCEL char(1) NOT NULL,
        STATEMENT_TYPE char(1) NOT NULL,
        AGENCY_CODE char(8) NOT NULL,
        AUDIT_BILL char(1) NOT NULL,
        AUDIT_PRINTED bit NOT NULL,
        PEND_CNCL_RPT_PRINTE char(1) NOT NULL,
        DEPOSITTRANSEXISTS bit NOT NULL
        );

    --create a BILLING_STATEMENT_CO table
    CREATE TABLE BILLING_STATEMENT_CO(
        POLICY_PREFIX_1 char(2) NOT NULL,
        POLICY_PREFIX_2 char(1) NOT NULL,
        POLICY_NUMBER decimal(11, 0) NOT NULL,
        POLICY_SUFFIX char(2) NOT NULL,
        STATEMENT_DATE datetime NULL,
        BILLING_INVOICE_NUMB int NOT NULL,
        COMMENT_LINE_1 char(80) NOT NULL,
        COMMENT_LINE_2 char(80) NOT NULL,
        COMMENT_LINE_STAR char(80) NOT NULL
    );
    
    
    CREATE TABLE WF_MAM_ERR_LOG(
		ID_ERR_LOG decimal(18, 0) NOT NULL PRIMARY KEY AUTO_INCREMENT,
		CYCLE_NUMBER decimal(10, 0) NOT NULL,
		SEQUENCE_NUMBER decimal(10, 0) NOT NULL,
		DESCRIPTION varchar(255) NOT NULL,
		STATUS varchar(20) NOT NULL
	);
	
--create POLICY_MASTER table
CREATE TABLE POLICY_MASTER(
	SUBMISSION_NUMBER int NOT NULL,
	POLICY_PREFIX_1 char(2) NOT NULL,
	POLICY_PREFIX_2 char(1) NOT NULL,
	POLICY_NUMBER decimal(11, 0) NOT NULL,
	POLICY_SUFFIX char(2) NOT NULL,
	SUBMISSION_DATE datetime NULL,
	RECEIVED_DATE datetime NULL,
	ISSUED_DATE datetime NULL,
	EFFECTIVE_DATE datetime NULL,
	EXPIRATION_DATE datetime NULL,
	NORMAL_ANNIV_DATE datetime NULL,
	STATUS_CODE int NOT NULL,
	STATUS_DATE datetime NULL,
	AGENCY_CODE char(8) NOT NULL,
	AGENCY_GROUP_CODE int NOT NULL,
	TERM int NOT NULL,
	CANCEL_DATE datetime NULL,
	CANCEL_TYPE int NOT NULL,
	REINSURANCE_TYPE_COD int NOT NULL,
	REINSTATEMENT_DATE datetime NULL,
	REINSTATE_W_LAPS_EFF datetime NULL,
	REINSTATE_W_LAPS_EXP datetime NULL,
	RENEWABLE_FLAG char(1) NOT NULL,
	NONREN_DATE datetime NULL,
	NONREN_CODE int NOT NULL,
	ADMIN_UNIT_CODE int NOT NULL,
	FINAL_AUDIT_FLAG char(1) NOT NULL,
	CLAIM_EXAMINER int NOT NULL,
	CSO int NOT NULL,
	DIRECT_COLLECTOR_COD char(8) NOT NULL,
	ASSIGNED_RISK char(1) NOT NULL,
	DATE_OF_NOTICE datetime NULL,
	FINANCE_COMPANY_CODE int NOT NULL,
	STANDARD_INDUSTRY_CO int NOT NULL,
	REASSIGNED char(1) NOT NULL,
	ASSUMED_FROM int NOT NULL,
	ASSUMED_POLICY_NO char(16) NOT NULL,
	AGENCY_ISSUED char(1) NOT NULL,
	BINDER_NUMBER decimal(18, 0) NOT NULL,
	WINNING_QUOTE_NUMBER int NOT NULL,
	NEXT_ENTITY_NUMBER int NOT NULL,
	FOR_CCURNCYBINDER bit NOT NULL,
	COMBINED_ID decimal(11, 0) NOT NULL,
	LOCKED bit NOT NULL,
	XUE_ENTERED bit NOT NULL
);

--create SPR_FINANCIAL_FILE table
CREATE TABLE SPR_FINANCIAL_FILE(
	SUBMISSION_NUMBER int NOT NULL,
	QUOTE_NUMBER int NOT NULL,
	QUOTE_DESCRIPTION char(30) NOT NULL,
	QUOTE_STATUS int NOT NULL,
	POLICY_PREFIX_ID int NOT NULL,
	POLICY_PREFIX_1 char(2) NOT NULL,
	POLICY_PREFIX_2 char(1) NOT NULL,
	GL_COMPANY_CODE int NOT NULL,
	SAFETY_GROUP_CODE int NOT NULL,
	SAFETY_GROUP_DATE datetime NULL,
	GOVERNING_CLASS_ID int NOT NULL,
	GOVERNING_CLASS_CODE int NOT NULL,
	GOVERNING_CLASS_SUFF char(2) NOT NULL,
	QUALITY_GRADE decimal(4, 2) NOT NULL,
	BILLING_TIMING_CODE int NOT NULL,
	RETRO_YN char(1) NOT NULL,
	RETRO_NUMBER_OF_YEAR int NOT NULL,
	PARTICIPATINGNON char(1) NOT NULL,
	PARTICIPATING_NUMBER int NOT NULL,
	MISC_EXPENSE_FACTOR decimal(4, 3) NOT NULL,
	MINIMUM_PREMIUM int NOT NULL,
	MINIMUM_PREMIUM_STAT char(2) NOT NULL,
	MINIMUM_PREMIUM_USLH char(1) NOT NULL,
	COMMISSION decimal(10, 9) NOT NULL,
	COMMISSION_PREMIUM int NOT NULL,
	MANUAL_EAP int NOT NULL,
	STANDARD_PREMIUM int NOT NULL,
	FINANCIAL_EAP int NOT NULL,
	BILLABLE_EAP int NOT NULL,
	DEPOSIT decimal(9, 8) NOT NULL,
	DEPOSIT_AMOUNT int NOT NULL,
	NUMBER_OF_INSTALLMEN int NOT NULL,
	NUMBER_OF_CHECKING_A int NOT NULL,
	FREQUENCY_CODE char(1) NOT NULL,
	AUDIT_CHECKING_FREQU char(1) NOT NULL,
	DELAY_CODE char(1) NOT NULL,
	AGYDIRECT_BILL_CODE char(1) NOT NULL,
	DATE_PRINTED datetime NULL,
	AUDIT_INVOICE_METHOD char(1) NOT NULL,
	AUDITINSTALLMENT char(1) NOT NULL,
	COLLATERALIZED_DEPOS char(1) NOT NULL,
	CHECK_WITH_PAYROLL char(1) NOT NULL,
	AUDIT_SOLICITATION_M char(1) NOT NULL,
	POLICY_MINIMUM_PREMIUM int NOT NULL,
	ASSESMENT_EAP decimal(11, 2) NOT NULL,
	GOVERNING_CLASS_OVER bit NOT NULL,
	COMM_PERCENT_OVERRID bit NOT NULL,
	DEFERRAL_PERCENTAGE decimal(9, 8) NOT NULL,
	DEFERRAL_AMOUNT int NOT NULL,
	DEFERRAL_PERCENT_OVE bit NOT NULL,
	RECALC_NEEDED bit NOT NULL,
	ORIG_SUBM_EFF_DATE datetime NULL,
	ORIG_SUBM_EXP_DATE datetime NULL,
	ORIG_SUBM_NAD datetime NULL,
	EXPENSE_CONST_AMT int NOT NULL,
	EXPENSE_CONST_STATE char(2) NOT NULL,
	EXPENSE_CONST_USLH char(1) NOT NULL
);
    
    

